#
# Makefile
#
# Version:	$Id: Makefile,v 1.2 2006/01/22 21:46:41 nbk Exp $
#

TARGET		= rlm_policy
SRCS		= rlm_policy.c parse.c evaluate.c
HEADERS		= rlm_policy.h
RLM_CFLAGS	=
RLM_LIBS	=

include ../rules.mak

$(LT_OBJS): $(HEADERS)
